### ISSUE TITLE
Adding libraries

### ISSUE THREAD

**Issue by plugboy** [suculent/arduino-docker-build#2]
thanks for the great stuff, I would like to try this as some of my coworkers are having trouble to build the firmware for the nodemcu

but as we also use different libraries like https://github.com/bblanchon/ArduinoJson and 
https://playground.arduino.cc/Code/StackList/

how should I edit the dockerfile? thanks

**Comment by suculent** [comment]
If you're using Arduino Core, it can be driven through the thinx.yml file in root of the project. I don't have any NodeMCU at hand to make an example, but with a little help of the boards.txt:

```
# for ArduinoCore-based NodeMCU 0.9 (ESP-12 Module) builds with 4M/1M SPIFFS

arduino:
  platform: espressif
  arch: esp8266
  board: ESP8266_NODEMCU
  flash_ld: eagle.flash.4m1m.ld
  f_cpu: 80
  flash_size: 4M
  libs:
    - ArduinoJSON
    - StackList
```

If you don't want to use Arduino Library manager (see `libs:` tag above), you can place your libraries into folder named 'lib' and builder will use it from there as seen in the https://github.com/suculent/thinx-firmware-esp8266-ino example.

You should not need to edit the Dockerfile. For the NodeMCU platform itself (LUA-based) there's another builder at https://github.com/suculent/nodemcu-docker-build
